# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fed3d800d4f1a36f57ee232bdec58b55d02bd185e82fe2f66762cf823dedf376a000fa4797d0958bab558c45ac5c210d613839a79aa2db777e7bc23c626c1ab

test:
  secret_key_base: 35b21eb079c80c9c238502d62a2b5dbfa38d0d4be80ea35aaa4139fd65b146ffb990a2321173a0b088192016ce221484c9d5ff70fe98084a0ddbaf8282883547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
