PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "turmas" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "nome" varchar, "disciplina_id" integer, "QtdeAlunos" integer, "obrigatoria" integer);
INSERT INTO "turmas" VALUES(1,'A',1,38, 0);
INSERT INTO "turmas" VALUES(2,'B',1,39, 1);
INSERT INTO "turmas" VALUES(3,'C',1,38, 1);
INSERT INTO "turmas" VALUES(4,'D',1,37, 0);
CREATE TABLE "total_de_bolsas" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "QTE" integer, "QTE_alocadas" integer);
INSERT INTO "total_de_bolsas" VALUES(1,2,0);
CREATE TABLE "candidatos" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "mencao" varchar, "aluno_id" integer, "avaliacao" integer);
INSERT INTO "candidatos" VALUES(1,'SS',1,3);
INSERT INTO "candidatos" VALUES(2,'MS',2,2);
INSERT INTO "candidatos" VALUES(3,'MS',3,2);
INSERT INTO "candidatos" VALUES(4,'MS',4,2);
CREATE TABLE "candidatos_turmas" ("candidato_id" integer NOT NULL, "turma_id" integer NOT NULL);
INSERT INTO "candidatos_turmas" VALUES(1,4);
INSERT INTO "candidatos_turmas" VALUES(2,2);
INSERT INTO "candidatos_turmas" VALUES(3,2);
INSERT INTO "candidatos_turmas" VALUES(4,3);
CREATE INDEX "index_turmas_on_disciplina_id" ON "turmas" ("disciplina_id");
COMMIT;
